//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Serialize, Deserialize};

#[derive(Clone, Debug, Serialize, Deserialize, Default, PartialEq, DeriveEntityModel)]
#[serde(default)]
#[sea_orm(table_name = "config_meta")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: i32,
    pub code: String,
    pub property: String,
    pub column_name: String,
    pub description: String,
    pub sort: i32,
    pub gmt_create: DateTime,
    pub gmt_modified: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
