GET http://localhost:3000/ConfigMeta

GET http://localhost:3000/ConfigMeta?app_id=platform&code=userType

GET http://localhost:3000/ConfigMeta/1

DELETE http://localhost:3000/ConfigMeta/1

PUT http://localhost:3000/ConfigMeta/101
content-type: application/json

{
  "description": "类型编码A",
  "sort": 15
}

POST http://localhost:3000/ConfigMeta
content-type: application/json

{
  "app_id": "platform",
  "code": "userType",
  "property": "addr",
  "column_name": "varchar5",
  "description": "地址",
  "sort": 10,
  "gmt_create": "2018-05-10T17:54:31",
  "gmt_modified": "2018-05-10T21:14:08"
}


GET http://localhost:3000/ConfigItem/userType

GET http://localhost:3000/ConfigItem/sex

GET http://localhost:3000/ConfigItem/userType/1

DELETE http://localhost:3000/ConfigItem/userType/1


POST http://localhost:3000/ConfigItem/userType
content-type: application/json

{
  "code": "testuser",
  "name": "测试用户",
  "description": "测试用户",
  "img": "1.jpg"
}

PUT http://localhost:3000/ConfigItem/userType/1
content-type: application/json

{
  "name": "普通用户AAA"
}
