GET http://localhost:3000/ConfigMeta

GET http://localhost:3000/ConfigMeta?app_id=platform&code=userType

GET http://localhost:3000/ConfigMeta/1

DELETE http://localhost:3000/ConfigMeta/1

PUT http://localhost:3000/ConfigMeta/101
content-type: application/json

{
  "description": "类型编码A",
  "sort": 15
}

POST http://localhost:3000/ConfigMeta
content-type: application/json

{
  "app_id": "platform",
  "code": "userType",
  "property": "addr",
  "column_name": "varchar5",
  "description": "地址",
  "sort": 10,
  "gmt_create": "2018-05-10 17:54:31",
  "gmt_modified": "2018-05-10 21:14:08"
}


GET http://localhost:3000/ConfigItem/userType

GET http://localhost:3000/ConfigItem/sex

GET http://localhost:3000/ConfigItem/userType/1

DELETE http://localhost:3000/ConfigItem/userType/1


POST http://localhost:3000/ConfigItem/userType
content-type: application/json

{
  "app_id": "platform",
  "meta_code": "userType",
  "parent_id": 0,
  "sort": 0,
  "varchar1": "user",
  "varchar2": "普通用户",
  "varchar3": "刚注册还未认证用户",
  "varchar4": "1.jpg",
  "varchar5": "",
  "text1": "",
  "text2": "",
  "text3": "",
  "decimal1": 0.0,
  "decimal2": 0.0,
  "decimal3": 0.0,
  "datetime1": "2022-10-17 07:36:08",
  "datetime2": "2022-10-17 07:36:08",
  "datetime3": "2022-10-17 07:36:08",
  "gmt_create": "2018-05-10 17:54:31",
  "gmt_modified": "2018-05-10 21:14:08"
}